### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by klieret** [asmeurer/blog#21]
Hi, a number of links on your blog appear to be broken.
For example, I wanted to bookmark your post on the Riemann hypothesis at https://www.asmeurer.com/posts/verifying-the-riemann-hypothesis-with-sympy-and-mpmath/ (or at least that's the link that appears in the title), but this leads to a 404 error.

**Comment by asmeurer** [comment]
Looks like an issue I didn't notice from rebuilding the site with an older version of Nikola. It should be fixed now.
